os: linux
dist: bionic
language: shell

jobs:
  include:
    - &docker-build
      stage: Docker build
      language: generic
      name: ros-base
      install: ci/build-docker-image.sh --image="ar13pit/$TRAVIS_JOB_NAME" --branch="$TRAVIS_BRANCH" --pull-request="$TRAVIS_PULL_REQUEST" --user="$DOCKER_HUB_USERNAME" --password="$DOCKER_HUB_PASSWORD"

    - <<: *docker-build
      name: ros-cuda
