#! /usr/bin/env bash

# Install dependencies
sudo apt install -y python3 python3-dev python3-pip build-essential
sudo -H pip3 install -U rosdep
pip3 install --user -U pip
hash -r
pip3 install --user -U rospkg rosinstall_generator rosinstall wstool vcstools catkin_pkg defusedxml cmake
pip3 install --user -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04 wxPython
pip3 install --user -U backports.ssl_match_hostname twisted
pip3 install --user -U git+https://github.com/catkin/catkin_tools.git

sudo rosdep init
rosdep update

# Setup the base workspace
cd $HOME
mkdir -p catkin_ws_python3
cp install_skip catkin_ws_python3/
cd catkin_ws_python3

catkin config --init -DCMAKE_BUILD_TYPE=Release -DPYTHON_VERSION=3 --install
rosinstall_generator desktop_full rosbridge_suite --rosdistro melodic --deps --tar > melodic-full.rosinstall
wstool init -j8 src melodic-full.rosinstall

export ROS_PYTHON_VERSION=3
export PYTHONPATH=/usr/lib/python3/dist-packages

# If ros is already installed with python2 support using apt sources, then use the following command to get
# a list of python packages to be installed
#
# rosdep install --simulate --reinstall --from-paths src --ignore-src | grep python | grep -v python3 | sed -e "s/.*sudo -H apt-get install //g" | sed -z "s/\n/ /g" | sed -e "s/python/python3/g"
#
# It will be better to install all python3 sources using pip instead of system and just use --no-recommend-install flag
# in the apt command for all the other packages

sudo ./install_skip $(rosdep check --from-paths src --ignore-src | grep python | grep -v python3 | sed -e "s/^apt\t//g" | sed -z "s/\n/ /g" | sed -e "s/python/python3/g")

rosdep install --from-paths src --ignore-src -y --skip-keys="$(rosdep check --from-paths src --ignore-src | grep python | sed -e "s/^apt\t//g" | sed -z "s/\n/ /g")"

find . -type f -exec sed -i 's/\/usr\/bin\/env[ ]*python/\/usr\/bin\/env python3/g' {} +

catkin build

source install/setup.bash
